sudo: false
language: python

python:
    - '3.4'
    - '3.5'
    - '3.6'

env:
    global:
        - PKCS11_MODULE=/home/travis/lib/softhsm/libsofthsm2.so
        - PKCS11_TOKEN_LABEL=TEST
        - PKCS11_TOKEN_PIN=1234

cache:
    - pip
    - ccache  # For SoftHSMv2

before_install:
    - pip install -U pip setuptools
    - pip install -r dev-requirements.txt
    # Install SoftHSMv2
    - curl https://dist.opendnssec.org/source/softhsm-2.2.0.tar.gz | tar -zxv
    - (cd softhsm-2.2.0 && ./configure --prefix=$HOME --disable-p11-kit && make all install CC="ccache gcc" CXX="ccache g++")

before_script:
    # Initialise a token on the SoftHSM
    - $HOME/bin/softhsm2-util --init-token --free --label TEST --pin 1234 --so-pin 5678
    # Build our extension
    - python setup.py build_ext -i

script: python -m unittest


deploy:
    provider: pypi
    user: danni
    password:
        secure: "A/W51+GTE9CBAm4m+1AVg11EAF63BUBrCXIonmYCdTT2htEGStk9AJnZGOinHPhwgJoWujBqgqyjqm8wJSvsmhyPSWxGk20lkCJOptcHdExu4FoSnLNNzAgPtZH5lLarkpvxB20J9hUUb4CQbgz5BWeNqFPvKigKFworCksRr9EM4J/Ys8tmkI2zwSTRDH2YAmhI/h8BWGpHMP+pNUsjlp9ZbDaxgNY85r7RloP07N5R0A7TPePH8wJzuGMDOv8dLazdr0epCbvFk+2CyJ7KiEJoX+SlS/2Hi7OKnmuf7QG2z2YyukLlJcP+IhRfzZDVgUeXwJbu24XAUdMoBS8OxId8dOKFla+GJScpWGpA9rO5vgItTAYLG7sd9HuveCtvUZxqbJd5teST4PdcxjjeO5LxYkgXKrLEo1dvDtPOm/veA0axFrXzlberJCKyN2T6grfM5QVUCORQnUYPnOqkYXMHFKSIUfa2mpfJ8NZaHR7jEbddU/PpQTHwlcehMtTx9IKQyfzillmhiXVc+UMOInFbEsU4oD9f0eP2fcs2dDB3ppR+Rdkh8bb80zH2r55Giu4Fv/WGcllwaYvMGkm6TBdod/Hva4sypJaLkLFDH6LQ0jOBHfPdFYKzEn16kZ1F4X+QWl6lKiz4XWAJI8Cf73y9Acj1Q+4MAHobkE/908M="
    server: https://pypi.python.org/pypi
    on:
        tags: true
        python: 3.6
